version: "3"
services:
  springboot:
    image: myapp1:latest
    ports:
      - "8089:8080"
   
    depends_on:
      - mysqldb
   frontend:
    image: 
    container_name: angular-ui

     ports:
        - "4200:80"
     depends_on:
         - springboot
 
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
  
    environment:
      - MYSQL_DATABASE=devv 
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

