version: "3"
services:
  springboot:
    image: myapp:latest
    ports:
      - "8089:8080"
   
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
  
    environment:
      - MYSQL_DATABASE=devv 
      - MYSQL_USER=root
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
