version: "3"
services:
  springboot:
    image: myapp:latest
    ports:
      - "8089:8080"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    networks:
      - employee-mysql
    environment:
       MYSQL_PASSWORD='root'
       MYSQL_ALLOW_EMPTY_PASSWORD='yes'
       MYSQL_DATABASE='devv'
       MYSQL_USER='root'

networks:
  employee-mysql:
