version: "3"
services:
  springboot:
    image: myapp:latest
    ports:
      - "8089:8080"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - employee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
  employee-mysql:
